### ISSUE TITLE
Can not find icons

### ISSUE THREAD

**Issue by ashvinbhagat** [alexdevero/instatron#3]
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from /Users/ashvinstech/Downloads/instatron-1.4.0/assets/icon.ico
    at App.createWindow (/Users/ashvinstech/Downloads/instatron-1.4.0/app.js:152:13)
    at Object.onceWrapper (events.js:273:13)
    at App.emit (events.js:187:15)

This is the error. i tried to solve i by replacing the icons with my own but again same issue

Please help...

**Comment by giovannicaligaris** [comment]
I'm having  the same issue

**Comment by WoodburyShortridge** [comment]
ran across this too.

use the native image:

`if (platform == 'darwin') {
  trayIcon = path.join(__dirname, 'assets/instagram-uploader-icon.png')
} else if (platform == 'win32') {
  trayIcon = path.join(__dirname, 'assets/instagram-uploader-icon.ico')
} else {
  trayIcon = path.join(__dirname, 'assets/instagram-uploader-icon.ico')
}

trayIcon = nativeImage.createFromPath(trayIcon);`

and add nativeImage to electron require

**Comment by alexdevero** [comment]
Fix in aede1176a41d5d4ca6ecb1efd276cfbf7a44aee9.
